grasps = {
    '010_hunyuan': 'Grasp succeeded on ground truth',
    '010_instantmesh': 'Grasp failed on ground truth',
    '010_trellis': 'Grasp succeeded on ground truth',
    '010_triposr': 'Grasp failed on ground truth',
    '033_hunyuan': 'Grasp succeeded on ground truth',
    '033_instantmesh': 'No successful grasps on reconstructed mesh',
    '033_trellis': 'Grasp failed on ground truth',
    '033_triposr': 'No successful grasps on reconstructed mesh',
    '035_hunyuan': 'Grasp succeeded on ground truth',
    '035_instantmesh': 'Grasp succeeded on ground truth',
    '035_trellis': 'Grasp failed on ground truth',
    '035_triposr': 'Grasp failed on ground truth',
    '061_hunyuan': 'Grasp failed on ground truth',
    '061_instantmesh': 'Grasp failed on ground truth',
    '061_trellis': 'Grasp failed on ground truth',
    '061_triposr': 'Grasp succeeded on ground truth',
    '065_hunyuan': 'Grasp succeeded on ground truth',
    '065_instantmesh': 'Grasp succeeded on ground truth',
    '065_trellis': 'Grasp succeeded on ground truth',
    '065_triposr': 'Grasp failed on ground truth',
}